name: CICD Workflow

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: release version
        run: |
          TAG_NAME=$(echo "${GITHUB_REF#refs/tags/}")
          NUMERIC_TAG=${TAG_NAME#v}
  
          if [ "$NUMERIC_TAG" == "${{ vars.PRODUCTION_VERSION }}" ]; then
              echo "Sementic Tag: $NUMERIC_TAG"
              echo "new_version=$NUMERIC_TAG" >> $GITHUB_ENV
              buildNumber=$((${{ vars.PRODUCTION_BUILD_NUMBER }} + 1))
              echo "BuildNumber Tag: $buildNumber"
              echo "buildNumber=$buildNumber" >> $GITHUB_ENV
          else
              echo "Sementic Tag: $NUMERIC_TAG"
              echo "new_version=$NUMERIC_TAG" >> $GITHUB_ENV
              buildNumber=1
              echo "BuildNumber Tag: $buildNumber"
              echo "buildNumber=$buildNumber" >> $GITHUB_ENV
          fi

      - name: agvtool1
        id: version
        run: |
          cd ios 
          echo "BuildNumber Tag: $buildNumber"
          echo "Sementic Tag: $new_version"
          echo 

      - name: Upload to TestFlight
        run: |
          curl -X PATCH -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" -H "Accept: application/vnd.github+json" https://api.github.com/repos/${{ github.repository }}/actions/variables/production_version -d '{"name": "production_version", "value": "'"$new_version"'"}'
          curl -X PATCH -H "Authorization: Bearer ${{ secrets.GH_TOKEN }}" -H "Accept: application/vnd.github+json" https://api.github.com/repos/${{ github.repository }}/actions/variables/production_build_number -d '{"name": "production_build_number", "value": "'"$buildNumber"'"}'
          echo New Sematic Version number is $new_version upload to TestFlight
  
