name: Semantic Versioning

on:
  workflow_dispatch:

jobs:
  version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run version script
        run: |
          chmod +x ./version.sh
          ./version.sh

