name: Get Release Version

on:
  push: 
    tags: 
      - 'v*'  

jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - name: Print Release Version
        run: |
          release_version=${{ github.ref  }}
          echo "Release Version: ${{ release_version }}" 
