name: CICD Workflow

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get the release tag
        run: |
          TAG_NAME=$(echo "${GITHUB_REF#refs/tags/}")
          echo "Release Tag: $TAG_NAME"
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
          echo cicd run by $GIT_COMMITTER_NAME
          echo branch name is $GITHUB_REF
          echo commit id is $GITHUB_SHA
          echo "branch is tag-2"

      - name: Print the tag in a bash script
        run: |
          echo "The release tag is $TAG_NAME"
