name: Semantic Versioning

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Install_version_deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install JQ
        run: sudo apt-get install jq -y 

      - name: Run version script
        run: |
          chmod +x ./version.sh
          ./version.sh

